# mqtts connection from the SensorBridge to the MQTT broker
listener 8883
protocol mqtt
socket_domain ipv4
certfile /mosquitto/config/mqtt-broker-internal.pem
keyfile /mosquitto/config/mqtt-broker-internal-key.pem

# websockets connection for Access Points (via traefik proxy)
listener 9001
protocol websockets
socket_domain ipv4

# Authentication settings
allow_anonymous false
password_file /mosquitto/config/mosquitto.pass