# Allow local Unix socket (used by psql, pg_isready without -h)
local all all               md5

# Reject all non-SSL connections (IPv4 & IPv6)
hostnossl all all 0.0.0.0/0 reject
hostnossl all all ::/0      reject

# Allow SSL connections with password auth
hostssl  all all 0.0.0.0/0  md5
hostssl  all all ::/0       md5
